frontend/django_frontend/django_frontend/urls.py
#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.urls import path, include

urlpatterns = [
    path('', include('weatherpage.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

frontend/django_frontend/urls.py
#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.urls import path, include

urlpatterns = [
    path('', include('weatherpage.urls')),
    path('^django_plotly_dash/', include('django_plotly_dash.urls'))
]

frontend/django_frontend/weatherpage/urls.py
#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.urls import path, register_converter

from . import views
from .converters import StationIDConverter
from .views import LatestDataView

register_converter(StationIDConverter, 'SSS')

app_name = 'weatherpage'
urlpatterns = [
    path('', views.main, name='index'),
    path('<SSS:station_id>/', views.main_for_station, name='index_station'),
    path('download/', views.download, name='download'),
    path('impress/', views.impress, name='impress'),
    path('policy/', views.policy, name='policy'),
    path('latest/', LatestDataView.as_view(), name='latest')
]

frontend/django_frontend/weatherpage/models.py
#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.db import models

# Create your models here.

frontend/django_frontend/weatherpage/forms.py
#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.forms import Form, ChoiceField


class LatestDataForm(Form):
    station = ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        station_choices = kwargs.pop('station_choices')

        super().__init__(*args, **kwargs)

        self.fields['station'].choices = station_choices

frontend/django_frontend/weatherpage/views.py
#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from datetime import datetime, timedelta, timezone
from locale import format_string
from os import environ

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import FormView

# noinspection PyUnresolvedReferences
from . import dash_download_page_app
# noinspection PyUnresolvedReferences
from . import dash_weatherpage_app
from .dash_weatherpage.backend_proxy import CachedBackendProxy
from .dash_weatherpage.dash_settings import BACKEND_URL, BACKEND_PORT, BACKEND_DO_USE_HTTPS
from .forms import LatestDataForm


def main(request):
    return render(request, 'weatherpage/weatherdata.html', context={'BRAND_NAME': environ.get('BRAND_NAME')})


# noinspection PyUnusedLocal
def main_for_station(request, station_id):
    return render(request, 'weatherpage/weatherdata.html', context={'BRAND_NAME': environ.get('BRAND_NAME')})


def download(request):
    return render(request, 'weatherpage/download.html', context={'BRAND_NAME': environ.get('BRAND_NAME')})


def impress(request):
    return render(request, 'weatherpage/impress.html', context={'BRAND_NAME': environ.get('BRAND_NAME')})


def policy(request):
    return render(request, 'weatherpage/policy.html', context={'BRAND_NAME': environ.get('BRAND_NAME')})


class LatestDataView(FormView):
    template_name = 'weatherpage/latest_data.html'
    form_class = LatestDataForm

    SPECIAL_SENSOR_IDS = ['direction', 'gusts', 'rain_last_hour', 'speed', 'wind_temperature', 'uv']
    GENERAL_SENSOR_ORDER = ['temperature', 'humidity', 'rain', 'dewpoint']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        station_id = self.kwargs.get('station_id', None)

        backend_proxy = CachedBackendProxy(BACKEND_URL, BACKEND_PORT, BACKEND_DO_USE_HTTPS)
        if not station_id:
            station_id = self._get_sorted_stations(backend_proxy)[-1]['value']
        available_sensors = self._get_available_sensors(backend_proxy)
        latest_data = backend_proxy.latest_data(station_id)

        if len(latest_data) > 0:
            sensor_data, special_sensor_data = self._get_human_readable_sensor_data(available_sensors, latest_data)

            time_point = datetime.fromisoformat(latest_data['timepoint'])

            context['time_point'] = time_point
            context['sensor_data'] = sorted(sensor_data, key=lambda d: d['description'])
            context['special_sensor_data'] = sorted(special_sensor_data, key=lambda d: d['description'])
            context['status'] = self._get_transmission_status(time_point)

        return context

    @staticmethod
    def _get_transmission_status(time_point):
        if (datetime.now(timezone.utc) - time_point) <= timedelta(minutes=10):
            return 'current'
        elif (datetime.now(timezone.utc) - time_point) <= timedelta(hours=1):
            return 'delayed'
        else:
            return 'interrupted'

    @staticmethod
    def _get_available_sensors(backend_proxy):
        available_sensors = backend_proxy.available_sensors()

        available_sensors[1]['rain_last_day'] = {'description': 'Regen (letzte 24 Stunden)', 'unit': 'mm'}
        available_sensors[1]['rain_last_hour'] = {'description': 'Regen (letzte Stunde)', 'unit': 'mm'}

        return available_sensors

    def _get_human_readable_sensor_data(self, available_sensors, latest_data):
        sensor_data = []
        special_sensor_data = []

        for sensor_id, value in latest_data.items():
            if sensor_id == 'timepoint':
                continue

            if sensor_id == 'temperature_humidity':
                for temp_humid_sensor_id, subsensors in value.items():
                    for subsensor_id, sub_value in subsensors.items():
                        sensor_data.append(self._get_subsensor_data(subsensor_id, temp_humid_sensor_id, sub_value,
                                                                    available_sensors))
            else:
                this_sensor_data = self._get_sensor_data(sensor_id, value, available_sensors)
                self._replace_sensor_descriptions(this_sensor_data)

                if sensor_id not in LatestDataView.SPECIAL_SENSOR_IDS:
                    sensor_data.append(this_sensor_data)
                else:
                    special_sensor_data.append(this_sensor_data)

        return sensor_data, special_sensor_data

    @staticmethod
    def _replace_sensor_descriptions(this_sensor_data):
        if this_sensor_data['description'] == 'Windböen':
            this_sensor_data['description'] = 'Böen (letzte 10 Minuten)'
        if this_sensor_data['description'] == 'Windgeschwindigkeit':
            this_sensor_data['description'] = 'Wind (letzte 10 Minuten)'

    @staticmethod
    def _get_subsensor_data(subsensor_id, temp_humid_sensor_id, last_value, available_sensors):
        if subsensor_id == 'temperature':
            short_subsensor_id = 'temp'
        elif subsensor_id == 'humidity':
            short_subsensor_id = 'humid'
        else:
            short_subsensor_id = subsensor_id
        this_sensor_id = f'{temp_humid_sensor_id}_{short_subsensor_id}'
        human_readable_name = available_sensors[1][this_sensor_id]['description']
        unit = available_sensors[1][this_sensor_id]['unit']

        return {'description': human_readable_name, 'value': LatestDataView._get_presented_value(last_value, unit)}

    @staticmethod
    def _get_sensor_data(sensor_id, last_value, available_sensors):
        human_readable_name = available_sensors[1][sensor_id]['description']
        unit = available_sensors[1][sensor_id]['unit']

        return {'description': human_readable_name, 'value': LatestDataView._get_presented_value(last_value, unit)}

    @staticmethod
    def _get_presented_value(last_value, unit):
        if last_value is None:
            presented_value = '-'
        else:
            if unit == '%' or unit == '°':
                presented_value = f'{format_string("%.1f", last_value)}{unit}'
            else:
                presented_value = f'{format_string("%.1f", last_value)} {unit}'

        return presented_value

    def get_initial(self):
        initial = super().get_initial()
        if 'station_id' not in self.kwargs:
            backend_proxy = CachedBackendProxy(BACKEND_URL, BACKEND_PORT, BACKEND_DO_USE_HTTPS)
            stations = self._get_sorted_stations(backend_proxy)
            initial['station'] = stations[-1]['value']
        else:
            initial['station'] = self.kwargs['station_id']

        return initial

    @staticmethod
    def _get_sorted_stations(backend_proxy):
        return sorted(backend_proxy.available_stations()[0], key=lambda d: d['label'])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        backend_proxy = CachedBackendProxy(BACKEND_URL, BACKEND_PORT, BACKEND_DO_USE_HTTPS)
        initial_dropdown_settings = []
        for entry in self._get_sorted_stations(backend_proxy):
            initial_dropdown_settings.append((entry['value'], entry['label']))
        kwargs['station_choices'] = initial_dropdown_settings

        return kwargs

    def form_valid(self, form):
        return HttpResponseRedirect(reverse('weatherpage:latest_station', kwargs={'station_id': form.data['station']}))

frontend/django_frontend/weatherpage/templates/weatherpage/base_generic.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
    {% block robots %}{% endblock %}
    {% block header %}<title>{{ BRAND_NAME }}</title>{% endblock %}
    {% include "weatherpage/css_imports.html" %}
</head>

<body class="d-flex flex-column min-vh-100">
{% include "weatherpage/navbar.html" %}

<div class="container-fluid px-3">
    {% block content %}{% endblock %}
</div>

{% include "weatherpage/footer.html" %}
</body>

{% include "weatherpage/js_imports.html" %}
{% block footer %}{% endblock %}
</html>

frontend/django_frontend/weatherpage/templates/weatherpage/css_imports.html
{% load static %}
<link rel="stylesheet" href="{% static 'weatherpage/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="{% static 'weatherpage/bootstrap-component-styles.css' %}">
<link rel="stylesheet" href="{% static 'weatherpage/dash-component-styles.css' %}">

frontend/django_frontend/weatherpage/templates/weatherpage/download.html
{% extends "weatherpage/base_generic.html" %}

{% block robots %}<meta name="robots" content="noindex">{% endblock %}

{% block header %}
    {% load plotly_dash %}
    <title>Download</title>
    {% plotly_header %}
{% endblock %}

{% block content %}
    {% plotly_direct name="dash-download" %}
{% endblock %}

{% block footer %}
    {% plotly_footer %}
{% endblock %}

frontend/django_frontend/weatherpage/templates/weatherpage/footer.html
<footer id="footer" class="page-footer small bg-light pt-2 pb-2 mt-auto">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-auto">
                <a class="text-reset text-decoration-none" href="{% url "weatherpage:impress" %}">Impressum</a>
            </div>
            <div class="col-auto">
                <a class="text-reset text-decoration-none" href="{% url "weatherpage:policy" %}">Datenschutz</a>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-auto">
                <p class="m-0 mt-1 p-0">© 2023 Ralf Rettig</p>
            </div>
        </div>
    </div>
</footer>

frontend/django_frontend/weatherpage/templates/weatherpage/impress.html
{% extends "weatherpage/base_generic.html" %}

{% block robots %}<meta name="robots" content="noindex">{% endblock %}

{% block header %}<title>Impressum</title>{% endblock %}

{% block content %}
    <div class="row justify-content-center m-2">
        <div class="col-lg-6">
            <h1>Impressum</h1>

            <h2>Angaben gemäß § 5 TMG</h2>

            <address>
                #### ########<br>
                ########## ### ##<br>
                ##### #########<br>
                ##########<br>
            </address>


            <h2>Kontakt</h2>

            <address>
                Telefon: #### / ## ## ##<br>
                E-Mail: info@######.##<br>
            </address>

            <h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV</h2>

            <address>
                #### ########<br>
                ########## ### ##<br>
                ##### #########<br>
                ##########<br>
            </address>

            <p>Quelle: <a href="https://www.e-recht24.de/muster-disclaimer.html">eRecht24</a></p>


            <h1>Haftung</h1>

            <h2>Haftung für Inhalte</h2>

            <p>Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für
                eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.
                Nach § 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht
                verpflichtet, übermittelte oder gespeicherte fremde Informationen zu
                überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige
                Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der
                Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon
                unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem
                Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei
                Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte
                umgehend entfernen.</p>


            <h2>Haftung für Links</h2>

            <p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren
                Inhalte wir keinen Einfluss haben. Deshalb können wir für diese
                fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte
                der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der
                Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung
                auf mögliche Rechtsverstöße überprüft. Rechtswidrige
                Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente
                inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte
                einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen
                werden wir derartige Links umgehend entfernen.</p>


            <h2>Urheberrecht</h2>

            <p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten
                unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und
                jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen
                der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads
                und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen
                Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden,
                werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche
                gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden,
                bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen
                werden wir derartige Inhalte umgehend entfernen.</p>

            <p>Quelle: <a href="https://www.e-recht24.de/muster-disclaimer.html">eRecht24</a></p>
        </div>
    </div>
{% endblock %}

frontend/django_frontend/weatherpage/templates/weatherpage/js_imports.html
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
        crossorigin="anonymous"></script>

frontend/django_frontend/weatherpage/templates/weatherpage/latest_data.html
{% extends "weatherpage/base_generic.html" %}

{% load crispy_forms_filters %}

{% block robots %}
    <meta name="robots" content="noindex">
{% endblock %}

{% block header %}<title>Neuste Wetterdaten</title>{% endblock %}

{% block content %}
    <div class="row m-2">
        <div class="col-12">
            <h1>Neuste Wetterdaten</h1>
        </div>
    </div>

    <div class="row m-2">
        <form method="post">
            {% csrf_token %}
            <div class="col-12 col-md-6 col-lg-2">
                {{ form|crispy }}
            </div>
            <div class="col-auto mt-3">
                <button class="btn btn-primary" type="submit">Auswählen</button>
            </div>
        </form>
    </div>
    <div class="row m-2">
        <div class="col-12 mt-4">
            <p><strong>Zeitpunkt:</strong> {{ time_point|date:'d.m.Y H:i' }}</p>
        </div>
        <div class="col-12">
            {% if status == 'current' %}
                <p><strong>Datenübertragung: </strong><span class="icon-green"><i class="bi bi-check-circle"></i>
                    aktuell</span></p>
            {% elif status == 'delayed' %}
                <p><strong>Datenübertragung: </strong><span class="icon-orange"><i
                        class="bi bi-exclamation-triangle"></i>
                    verzögert</span>
                </p>
            {% else %}
                <p><strong>Datenübertragung: </strong><span class="icon-red"><i class="bi bi-exclamation-circle"></i>
                    gestört</span>
                </p>
            {% endif %}
        </div>
    </div>

    <div class="row m-2">
        <div class="col-12">
            <div class="mt-4">
                <div id="accordion">
                    <div class="card">
                        <div class="card-header" id="headingGeneral">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseGeneral"
                                    aria-expanded="true" aria-controls="collapseGeneral">
                                Allgemeine Sensoren
                            </button>
                        </div>
                        <div id="collapseGeneral" class="collapse show" aria-labelledby="headingGeneral"
                             data-parent="#accordion">
                            <div class="card-body row">
                                {% for dataset in sensor_data %}
                                    <div class="col-7 col-md-4">
                                        <p>{{ dataset.description }}:</p>
                                    </div>
                                    <div class="col-5 col-md-2">
                                        <p>{{ dataset.value }}</p>
                                    </div>
                                {% endfor %}
                            </div>

                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingSpecial">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseSpecial"
                                    aria-expanded="true" aria-controls="collapseSpecial">
                                Spezielle Sensoren
                            </button>
                        </div>
                        <div id="collapseSpecial" class="collapse" aria-labelledby="headingSpecial"
                             data-parent="#accordion">
                            <div class="card-body row">
                                {% for dataset in special_sensor_data %}
                                    <div class="col-7 col-md-4">
                                        <p>{{ dataset.description }}:</p>
                                    </div>
                                    <div class="col-5 col-md-2">
                                        <p>{{ dataset.value }} {{ dataset.unit }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

frontend/django_frontend/weatherpage/templates/weatherpage/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary px-3">
    <a class="navbar-brand" href="{% url "weatherpage:index" %}">{{ BRAND_NAME }}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-right" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Wetterdaten
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "weatherpage:index" %}">Alle Daten</a>
                    <a class="dropdown-item" href="{% url "weatherpage:latest" %}">Neuste Daten</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "weatherpage:download" %}">Download</a>
            </li>
        </ul>
    </div>
</nav>

frontend/django_frontend/weatherpage/templates/weatherpage/weatherdata.html
{% extends "weatherpage/base_generic.html" %}

{% block header %}
    {% load plotly_dash %}
    <title>Wetterdaten</title>
    {% plotly_header %}
{% endblock %}

{% block content %}
    {% plotly_direct name="dash-frontend" %}
{% endblock %}

{% block footer %}
    {% plotly_footer %}
{% endblock %}